export type UserRow = {
    id: string;
    name: string;
    username: string | null;
    email: string;
    avatar: string | null;
    status: string;
    locale: string;
    timezone: string;
    roles: string[];
    permissions: string[];
    is_reserved: boolean;
    is_delete_protected: boolean;
    reserved_key: string | null;
    last_login_at: string | null;
    last_login_ip: string | null;
    deleted_at: string | null;
    created_at: string;
    updated_at: string;
    form?: UserFormData;
};

export type UserFormData = {
    id: string;
    name: string;
    username: string | null;
    email: string;
    avatar: string | null;
    status: string;
    timezone: string;
    locale: string;
    roles: string[];
    permissions: string[];
    is_reserved: boolean;
    is_delete_protected: boolean;
    reserved_key: string | null;
    email_verified_at: string | null;
    last_login_at: string | null;
    last_login_ip: string | null;
    deleted_at: string | null;
    created_at: string;
    updated_at: string;
};
